prometheus:
  prometheusSpec:
    storageSpec:
      volumeClaimTemplate:
        spec:
          resources:
            requests:
              storage: 5Gi

    thanos:
      objectStorageConfig:
        existingSecret:
          name: thanos-objstore-secret
          key: objstore.yml

    thanosService:
      enabled: true   # Thanos Sidecar 서비스 활성화

# ingress:
#   enabled: true
#   hosts:
#     - "prometheus.example.com"

grafana:
  enabled: false
  adminPassword: song
# ingress:
#   enabled: true
#   hosts:
#     - "grafana.example.com"
